server:
  port: 8082
spring:
  datasource:
      url: jdbc:mysql://10.10.10.16:3306/ktkefu?useUnicode=true&characterEncoding=UTF-8
      username: kefu
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  jpa:
#    show-sql: true
logging:
  level.com.kefu: INFO
  level.com.skytech: INFO
  level.org.elasticsearch: INFO
  level.com.skytech.kefu.common.service.redisson: 'OFF'
#  level.org.springframework.web: DEBUG
#  level.com.kefuwebim.web.model.UKeFuDic: ERROR
#  level.org.hibernate.SQL: DEBUG
#  level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  level.trace: 'OFF'
  level.info: 'OFF'
  level.warn: 'OFF'
  level.error: 'OFF'
  level.debug: 'OFF'
  level.accessLog: 'OFF'
  level.serviceStatsLog: 'OFF'
  level.profile: 'OFF'
  level: info

skytech:
  kefu:
    url: http://localhost:8080
  mail:
    allow: true
    serviceOrderReceiver: jianfeng.jin@ketianyun.com,kurt.ding@ketianyun.com
    titlePrefix: 开发环境
    arrearageReceiver: jianfeng.jin@ketianyun.com
    balanceReceivers: kurt.ding@ketianyun.com,qinmei.ye@ketianyun.com,jun.zhang@ketianyun.com
    balanceQinqin: kurt.ding@ketianyun.com
    balanceBusiness: kurt.ding@ketianyun.com
    orgAccountError: kurt.ding@ketianyun.com
    currentFeeUnknownError: kurt.ding@ketianyun.com
    currentFeeError: kurt.ding@ketianyun.com
redis:
  mode: single
  host: 127.0.0.1
  port: 6379
  database: 0
  password:
  clientName: admin
  connectionPoolSize: 64
  connectionMinimumIdleSize: 32
  idleConnectionTimeout: 10000
  retryAttempts: 3
  retryInterval: 1500

asr:
  recordingconvert:
    size: 10
    from: 80
    to: 180

alibaba:
  asr:
    prefix_url : http://sky-techcloud.com/recordings/
    ak_id : LTAIx741D1JQhyK5
    ak_secret: YHXyugPaZLYq5UDmVpN5KT1TxAzkFK

quality:
  check:
    host: 10.10.10.66
    port: 8082
    isDelete: 0
    status: 1
    appKey: 1
    rules: 1001|1002|1003|1004|1005|1006|1007|1008|1011|1012|1013|1014|1015|1016|1017|1018|1019|1020|1021|1022|1023|1024|1025|1026|1027

elasticsearch:
  index:
    calldetailname : testdb
    asrname : newasr
    kefuname: uckefu
    qualityname: quality
    statusname: agent_history_status

  type:
    calldetailmisscalltype : calldetailmisscall
    calldetailtype : call
    asrchanneltype : asr_channel
    asrtasktype : asr_task
    contactstype: uk_contacts
    callplantype: uk_callplan
    calltasktype: uk_calltask
    callusertype: uk_calluser
    entcustomertype: uk_entcustomer
    favoritestype: uk_favorites
    feedbacktype: uk_feedback
    workordertype: uk_workorders
    workordercommenttype: uk_workorders_comments
    workorderstranstype: uk_workorders_trans
    rulestype: rules
    scoreitemtype: score_item
    subscoreitemtype: sub_score_item
    kefustatustype: agent_history_status
    realtimechanneltype: asrchannel_realtime
  quality:
    rule: 测试规则
cron:
  chargeOffCron: 0 30 1 1 * ?
  checkMonthCron: 0 50 1 * * ?
  checkAccountCron: 0 0 2 * * ?
  checkRentCron: 0 18 15 10 * ?
    #3点有个Jeff出账的job
  reduceBalance: 0 30 2 9 * ?
  currentFee: 0 50 2 * * ?

  sendEmail:  0 0 8 * * ?
  ruleAsyncShedule: 0 0 * * * ?
  fileConvertSchedule: 0 0 5 * * ?